services:
  - type: web
    name: attendance-system
    env: python
    region: oregon
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn attendance_system.wsgi:application --workers 1 --bind 0.0.0.0:10000
    envVars:
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.13.4
